---
title: ""
page-layout: full
toc: false
body-classes: homepage
---
:::: {.container-texto}

:::: {.carousel}

:::: {.carousel-item image="assets/imgs/image.jpeg" caption="Tucano"}
:::

:::: {.carousel-item image="assets/imgs/image2.jpeg" caption="Carcará"}
:::

:::: {.carousel-item image="assets/imgs/image3.jpeg" caption="Jacu"}
:::

:::: {.carousel-item image="assets/imgs/image4.jpeg" caption="Quero-Quero"}
:::

:::: {.carousel-item image="assets/imgs/image5.jpeg" caption="Pica-Pau"}
:::

:::: {.carousel-item image="assets/imgs/image6.jpeg" caption="Gavião-Branco"}
:::

:::: {.carousel-item image="assets/imgs/image7.jpeg" caption="Tucano"}
:::

:::: {.carousel-item image="assets/imgs/image8.jpeg" caption="Thales !?"}
:::

:::

## Banco de Dados de Tintas Artísticas

#### O Projeto

Localizado no Instituto de Pesquisas Energéticas e Nucleares - IPEN, o Laboratório de Espectroscopia e Espectrometria das Radiações - LEER há alguns anos realiza pesquisas de caracterização elementar de materiais pertencentes ao patrimônio Artístico e Cultural. Desta forma, o **Projeto Banco de Dados Tintas Artísticas** tem como objetivo estruturar, armazenar e analisar informações técnicas, químicas e cromáticas de tintas utilizadas em arte, possuindo fins de conservação e pesquisa científica. 

#### Dados Técnicos

O banco de dados possui estudos de caracterização elementar utilizando diferentes técnicas, como a Fluorescência de Raios - X (FRX) e a Análise por Ativação Neutrônica (AAN). Como também, possui registro dos respectivos espectros e resultados das distribuições dos elementos em gráficos.

#### Público-Alvo

O público-alvo são pesquisadores em conservação e restauro; artistas; estudantes de artes e química e todos que buscam um local centralizado para encontrar dados detalhados de caracterização elemental de tintas artísticas.

---

## Funcionalidades

#### De Busca

Realize uma consulta detalhada de tintas artísticas por meio de:

- Nome;
- Rótulo na embalagem;
- Cor;
- Década;
- Técnica de análise utilizada;
- Tipo de Medium.

#### De Análise

Ainda faça uma:

- Descoberta dos elementos presentes em cada tinta;
- Visualização gráfica de distribuição dos elementos;
- Comparação entre diferentes técnicas.  

---

:::
